# Generated by Django 4.2.8 on 2023-12-17 13:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0002_alter_contributor_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='birth_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1000, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2023, 12, 17))]),
        ),
    ]
